
DECLARE
	codServicio NUMBER(12);
	codConcepto NUMBER(12);
	codCriterio NUMBER(12);
	codDepenCriterioCliente NUMBER(12);
	codDependenciaCriterio NUMBER(12);

	codCriterioPadre1 NUMBER(12);

	codEquivalencia NUMBER(12);
	codConexionParametro NUMBER(12);
	codDetalleConexion NUMBER(12);
	codExcepcionAccino NUMBER(12);
	codNiveles NUMBER(12);
	codServicioAsignado NUMBER(12);
	codMsjRespServicio NUMBER(12);

BEGIN
	-- se define en el router main /staging / srv_servicios (coordinacion) 
	codServicio:= 704;  -- id servicio para saguapac

	-- cod cliente pedir al canal transactional ya que debera tener una cuenta  
	-- permite multiples conceptos N
    -- pasarela NULL
	-- EN LINEA 1
   	-- TIENE DATOS ADICIONALES 1 -- SAGUAPAC
	INSERT INTO GANADERO.SRV_SERVICIOS (IDENTIFICADOR, COD_EXTERNO, COD_CLIENTE, COD_TIPO_SERVICIO, EMAIL_NOTIFICACIONES, COD_MEDIO_ENV_INFO, COD_VIA_ENV_ENTREGA, COD_SUBTIPO_SERVICIO, COD_SUCURSAL_MATRIZ, COD_AGENDAS_DE_ATENCION, APLICA_CAMBIO_MONEDA, COD_TIPO_ABONO_PROVEEDOR, USA_CTA_MULTIPLE, TIENE_DEUDOR_AFILIADO, COD_TIPO_COMPROBANTE, COD_TIPO_FORMATO_COMPROBANTE, COD_FORMATO_COMPROBANTE, COD_TIPO_FACTURACION, COD_TIPO_FORMATO_FACTURA, COD_FORMATO_FACTURA, PERMITE_PAGO_ADELANTADO, PERMITE_PAGO_PARCIAL, COD_PERIODO_COBRO, TIENE_BENEFICIO_PAGO_ADEL, TIENE_PLAN_PAGO, NRO_TOTAL_CUOTAS, APLICA_MORA, RECAUDACION_MONTO_DEFINIDO, TIENE_GESTION, FORMATO_PERIODO, PERMITE_FACTURA_FECHA_FIJA, DIA_CORTE_DE_FACTURACION, FECHA_HABILITACION_SERVICIO, PERMITE_MODIF_NOMBRE_NIT, COD_TIPO_GENERACION_FACTURA, PERIODO_TRANSFERENCIA_DIAS, ESTA_CONTINGENCIA, MENSAJE_CONTINGENCIA, COD_ESTADO, USUARIO_REGISTRO, SUCURSAL_REGISTRO, FECHA_REGISTRO, USUARIO_MODIFICACION, SUCURSAL_MODIFICACION, FECHA_MODIFICACION, TZ_LOCK, COD_ESTADO_PARAM_FUNCIONAL, NOMBRE_SERVICIO, FORMATO_FECHA, VERIFICA_AFILIACION_EXTERNA, COD_GENERACION_TXN_PAGO, FORMATO_HORA, ES_SERVICIO_NUEVO, PERMITE_AGRUPACION_CONCEPTO, COD_REFERENCIA, TIPO_CAMBIO_FACTURA, METODO_DOCUMENTO, PERMITE_PAGOS_PENDIENTES_X_REG, ENLINEA, TIENE_DATOS_ADICIONALES, FACTURA_MSJ, ES_SERVICIO_SIN_AFILIACION, COD_TIPO_SINCRONIZACION, PERMITE_FACTURA_EN_CONTINGENCIA, TIENE_PRIORIDAD_DE_ENVIO_FACTURA, PERMITE_CONCEPTO_MULTIPLE)
	VALUES(codServicio, TO_CHAR(codServicio), 5484049, 'C', NULL, 'S', 'G', 2, 701, 1, 'N', 'C', 'N', 'N', 'T', NULL, 1, 'NF', 'G', 1, 'N', 'N', NULL, NULL, 'N', NULL, 'N', 'N', 'N', 'YYYY-MM', 'N', NULL, SYSDATE, 'S', 'I', NULL, 'N', NULL, 'A', 'TOP1', 701, SYSDATE, NULL, NULL, NULL, 0, 'HF', 'TIGO', 'yyyymmdd', 'S', 'A', 'hhmmss', 'S', 'N', '1', 1, 'N', 'N', 1, 1, NULL, 'N', 'N', NULL, NULL, 'N');

	codConcepto:= SEQ_SRV_CONCEPTOS.nextval;

	INSERT INTO GANADERO.SRV_CONCEPTOS (IDENTIFICADOR, COD_SERVICIO, DESCRIPCION, PRIORIDAD, ABREVIATURA_CONCEPTO, COD_ESTADO, TZ_LOCK, GENERA_FACTURA, MONTO_DEFINIDO, ID_CONCEPTO, ES_POR_CANTIDAD)
	VALUES(codConcepto, codServicio, 'RECAUDACION', 1, 'RECAUD', 'A', 0, 'N', 0, 1, 'N');
	
	-- SALDO_JTS_OID DEL CLIENTE SAGUAPAC 
	-- SALDO_JTS_OID_ENTE FINAL DEL DIA NULL PARA QUE SEA CADA PAGO 
	INSERT INTO GANADERO.SRV_SERVICIOS_SALDOS (COD_SERVICIO, MONEDA, COD_CONCEPTO, SALDO_JTS_OID, TIPO_SERVICIO, MORA, ACEPTA_PAGO_PARCIAL, REINTENTO_COBRO, DIAS_REINTENTO, SALDO_JTS_OID_ENTE, CONCEPTO_HABILITADO, VALOR_MORA, M_ACUMULA, SALDO_JTS_OID_SECOND, SALDO_JTS_OID_ENTE_SECOND, TZ_LOCK, IDENTIFICADOR)
	VALUES(codServicio, 0, codConcepto, 4535313, 0, 'N', 'N', 'N', 999, 1723666, 'A', 0, 'N', 0, 0, 0, SEQ_SRV_SERVICIOS_SALDOS.NEXTVAL);
	DBMS_OUTPUT.PUT_LINE('1. Servicio insertado correctamente');
	-- abriatura y alias deben ser los mismos --TODO VERIFICAR LA LONGITUD PERMITIDA
	-- ============================================
	-- 1. Criterio Padre 1
	-- ============================================
	SELECT MAX(IDENTIFICADOR) + 1 INTO codCriterio FROM GANADERO.SRV_CRITERIOS_DE_BUSQUEDA;
	
	codCriterioPadre1 := codCriterio;
	
	-- ============================================
	-- 2. Criterio de codigoSocio
	-- ============================================
	INSERT INTO GANADERO.SRV_CRITERIOS_DE_BUSQUEDA (
	    IDENTIFICADOR, COD_SERVICIO, COD_TIPO_DATO, ES_OBLIGATORIO,
	    ETIQUETA_CRITERIO, LONGITUD_MINIMA, METODO_BUSQUEDA, VALORES,
	    VALOR_X_DEFECTO, ORDINAL, ABREVIATURA, DESCRIPCION, COD_ACCION,
	    TZ_LOCK, ALIAS, ES_SUBSERVICIO, COD_ESTADO, LONGITUD_MAXIMA,
	    COD_EXTERNO, TIENE_PARAMETROS, COD_FLUJO_HAB
	)
	VALUES (
	    codCriterioPadre1, codServicio, 2, 'S', 'CODIGO SOCIO', 1, 0,
	    NULL, NULL, 1, '1', 'CODIGO SOCIO', 10, 0, 'codigoSocio',
	    'N', 'A', 15, 1, 0, 1
	);
	
	-- ============================================
	-- 4. Dependencias para Padre 1
	-- ============================================
	SELECT MAX(IDENTIFICADOR) + 1 INTO codDependenciaCriterio
	FROM GANADERO.SRV_DEPENDENCIA_CRITERIO_BUSQUEDA;
	
	codDependenciaCriterio := codDependenciaCriterio + 1;
	INSERT INTO GANADERO.SRV_DEPENDENCIA_CRITERIO_BUSQUEDA
	VALUES (codDependenciaCriterio, codCriterioPadre1, codCriterioPadre1, 'A', 2, 0, 0);

	
DBMS_OUTPUT.PUT_LINE('3. Servicio insertado correctamente');
	-- SRV_TIPOS EQUIVALENCIA
	SELECT MAX(IDENTIFICADOR) + 1 INTO codEquivalencia FROM GANADERO.SRV_TIPOS_EQUIVALENCIA;
	INSERT INTO GANADERO.SRV_TIPOS_EQUIVALENCIA (IDENTIFICADOR, COD_SERVICIO, COD_TIPO_PARAMETRO, VALOR_TOPAZ, VALOR_EMPRESA)
	VALUES(codEquivalencia, codServicio, 1, '0', 'BOB');
	
    -- datos del request 
	SELECT MAX(IDENTIFICADOR) + 1 INTO codDetalleConexion FROM GANADERO.SRV_DETALLE_CONEXION;
	INSERT INTO GANADERO.SRV_DETALLE_CONEXION (IDENTIFICADOR, COD_SERVICIO, LLAVE, VALOR, COD_ACCION, COD_TIPO_CONEXION, COD_ESTADO, ORDINAL, USUARIO_REGISTRO, SUCURSAL_REGISTRO, FECHA_REGISTRO, USUARIO_MODIFICACION, SUCURSAL_MODIFICACION, FECHA_MODIFICACION, TZ_LOCK)
	VALUES(codDetalleConexion, codServicio, 'codAplicacion', '2', 1, 'E', 'A', 3, 'JBK', 701, SYSDATE, NULL, NULL, NULL, 0);
	
	codDetalleConexion := codDetalleConexion + 1;
	INSERT INTO GANADERO.SRV_DETALLE_CONEXION (IDENTIFICADOR, COD_SERVICIO, LLAVE, VALOR, COD_ACCION, COD_TIPO_CONEXION, COD_ESTADO, ORDINAL, USUARIO_REGISTRO, SUCURSAL_REGISTRO, FECHA_REGISTRO, USUARIO_MODIFICACION, SUCURSAL_MODIFICACION, FECHA_MODIFICACION, TZ_LOCK)
	VALUES(codDetalleConexion, codServicio, 'codSucursal', '70', 1, 'E', 'A', 3, 'JBK', 701, SYSDATE, NULL, NULL, NULL, 0);
	
	codDetalleConexion := codDetalleConexion + 1;
	INSERT INTO GANADERO.SRV_DETALLE_CONEXION (IDENTIFICADOR, COD_SERVICIO, LLAVE, VALOR, COD_ACCION, COD_TIPO_CONEXION, COD_ESTADO, ORDINAL, USUARIO_REGISTRO, SUCURSAL_REGISTRO, FECHA_REGISTRO, USUARIO_MODIFICACION, SUCURSAL_MODIFICACION, FECHA_MODIFICACION, TZ_LOCK)
	VALUES(codDetalleConexion, codServicio, 'codUsuario', 'JBK', 1, 'E', 'A', 3, 'JBK', 701, SYSDATE, NULL, NULL, NULL, 0);
	
	codDetalleConexion := codDetalleConexion + 1;
	INSERT INTO GANADERO.SRV_DETALLE_CONEXION (IDENTIFICADOR, COD_SERVICIO, LLAVE, VALOR, COD_ACCION, COD_TIPO_CONEXION, COD_ESTADO, ORDINAL, USUARIO_REGISTRO, SUCURSAL_REGISTRO, FECHA_REGISTRO, USUARIO_MODIFICACION, SUCURSAL_MODIFICACION, FECHA_MODIFICACION, TZ_LOCK)
	VALUES(codDetalleConexion, codServicio, 'serviceId', codServicio, 1, 'E', 'A', 3, 'JBK', 701, SYSDATE, NULL, NULL, NULL, 0);
	
	codDetalleConexion := codDetalleConexion + 1;
	INSERT INTO GANADERO.SRV_DETALLE_CONEXION (IDENTIFICADOR, COD_SERVICIO, LLAVE, VALOR, COD_ACCION, COD_TIPO_CONEXION, COD_ESTADO, ORDINAL, USUARIO_REGISTRO, SUCURSAL_REGISTRO, FECHA_REGISTRO, USUARIO_MODIFICACION, SUCURSAL_MODIFICACION, FECHA_MODIFICACION, TZ_LOCK)
	VALUES(codDetalleConexion, codServicio, 'codCliente', codServicio, 1, 'E', 'A', 3, 'JBK', 701, SYSDATE, NULL, NULL, NULL, 0);
	
	codDetalleConexion := codDetalleConexion + 1;
	INSERT INTO GANADERO.SRV_DETALLE_CONEXION (IDENTIFICADOR, COD_SERVICIO, LLAVE, VALOR, COD_ACCION, COD_TIPO_CONEXION, COD_ESTADO, ORDINAL, USUARIO_REGISTRO, SUCURSAL_REGISTRO, FECHA_REGISTRO, USUARIO_MODIFICACION, SUCURSAL_MODIFICACION, FECHA_MODIFICACION, TZ_LOCK)
	VALUES(codDetalleConexion, codServicio, 'codNegocio', codServicio, 1, 'E', 'A', 3, 'JBK', 701, SYSDATE, NULL, NULL, NULL, 0);
	
	
	-- select para el login con el proveedor
	SELECT MAX(IDENTIFICADOR) + 1 INTO codExcepcionAccino FROM  GANADERO.SRV_EXCEPCIONES_DE_ACCION ;
	INSERT INTO GANADERO.SRV_EXCEPCIONES_DE_ACCION (IDENTIFICADOR, COD_SERVICIO, COD_ACCION, COD_ESTADO, USUARIO_REGISTRO, SUCURSAL_REGISTRO, FECHA_REGISTRO, USUARIO_MODIFICACION, SUCURSAL_MODIFICACION, FECHA_MODIFICACION)
	VALUES(codExcepcionAccino, codServicio, 1, 'A', 'TOP1', 701, SYSDATE, NULL, NULL, NULL);
	
	-- select max pendiente 
	SELECT MAX(IDENTIFICADOR) + 1 INTO codNiveles FROM GANADERO.SRV_NIVELES;
	INSERT INTO GANADERO.SRV_NIVELES (IDENTIFICADOR, COD_SERVICIO, ABREVIATURA, DESCRIPCION, GESTION, COD_ESTADO, USUARIO_REGISTRO, SUCURSAL_REGISTRO, FECHA_REGISTRO, USUARIO_MODIFICACION, SUCURSAL_MODIFICACION, FECHA_MODIFICACION, TZ_LOCK, ORDINAL)
	VALUES(codNiveles, codServicio, 'TIGO', 'TIGO', 2024, 'A', 'TOP1', 701, SYSDATE, 'TOP1', 701, SYSDATE, 0, NULL);
	
	DBMS_OUTPUT.PUT_LINE('4. Servicio insertado correctamente');
	-- SELECT MAX PENDIENTE GANADERO.SRV_SERVICIOS_ASIGNADOS
	SELECT MAX(IDENTIFICADOR) + 1 INTO codServicioAsignado FROM GANADERO.SRV_SERVICIOS_ASIGNADOS;

	INSERT INTO GANADERO.SRV_SERVICIOS_ASIGNADOS (IDENTIFICADOR, COD_SERVICIO, COD_SERVICIO_WEB, COD_ESTADO, ALIAS, USUARIO_REGISTRO, SUCURSAL_REGISTRO, FECHA_REGISTRO, USUARIO_MODIFICACION, SUCURSAL_MODIFICACION, FECHA_MODIFICACION, TZ_LOCK, PETICION_FORMATO_ACEPTACION, PETICION_CUERPO, PETICION_SOAP_ACTION, METODO_PETICION, PETICION_TIPO_CONTENIDO, ETIQUETA_RESPUESTA, COD_FORMATO, ETIQUETA_CODIGO_ERROR, ETIQUETA_MSJ_ERROR, SERVICIO_ES_PADRE, COD_PADRE, ORDINAL, COD_TIPO_AUTORIZACION, METODO_DOCUMENTO)
	VALUES(codServicioAsignado, codServicio, 131, 'A', 'criterioBusqueda', 'WEB', 701, SYSDATE, NULL, NULL, NULL, 0, 'application/json', NULL, NULL, 'POST', NULL, NULL, 1, 'errCode', 'errMsg', 'N', NULL, NULL, NULL, 'N');
	-- MAPEO DE MSJ AL CLIENTE criterioBusqueda
	SELECT MAX(IDENTIFICADOR) + 1 INTO codMsjRespServicio FROM GANADERO.SRV_MSJ_RESPUESTAS_SERVICIO;
	INSERT INTO GANADERO.SRV_MSJ_RESPUESTAS_SERVICIO (IDENTIFICADOR, COD_SERVICIO_ASIGNADO, COD_ERROR, MENSAJE_TECNICO, MENSAJE_USUARIO, COD_EAP_MENSAJE_DEFINICIONES, COMENTARIO_MENSAJE, USUARIO_REGISTRO, SUCURSAL_REGISTRO, FECHA_REGISTRO, USUARIO_MODIFCACION, SUCURSAL_MODIFICACION, FECHA_MODIFICACION, TZ_LOCK, COD_TIPO_MENSAJE)
	VALUES(codMsjRespServicio, codServicioAsignado, ' ', 'Codigo Exitoso', 'Codigo Exitoso', 14, 'Ninguno', 'TOP1', 701, SYSDATE, NULL, NULL, NULL, 0, 'C');
	

	codServicioAsignado := codServicioAsignado + 1;
	codMsjRespServicio := codMsjRespServicio + 1;
	INSERT INTO GANADERO.SRV_SERVICIOS_ASIGNADOS (IDENTIFICADOR, COD_SERVICIO, COD_SERVICIO_WEB, COD_ESTADO, ALIAS, USUARIO_REGISTRO, SUCURSAL_REGISTRO, FECHA_REGISTRO, USUARIO_MODIFICACION, SUCURSAL_MODIFICACION, FECHA_MODIFICACION, TZ_LOCK, PETICION_FORMATO_ACEPTACION, PETICION_CUERPO, PETICION_SOAP_ACTION, METODO_PETICION, PETICION_TIPO_CONTENIDO, ETIQUETA_RESPUESTA, COD_FORMATO, ETIQUETA_CODIGO_ERROR, ETIQUETA_MSJ_ERROR, SERVICIO_ES_PADRE, COD_PADRE, ORDINAL, COD_TIPO_AUTORIZACION, METODO_DOCUMENTO)
	VALUES(codServicioAsignado, codServicio, 512, 'A', 'pagos', 'WEB', 701, SYSDATE, NULL, NULL, NULL, 0, 'application/json', NULL, NULL, 'POST', NULL, NULL, 1, 'errCode', 'errMsg', 'N', NULL, NULL, 'A', 'N');	
	-- MAPEO DE MSJ AL CLIENTE pagos
	INSERT INTO GANADERO.SRV_MSJ_RESPUESTAS_SERVICIO (IDENTIFICADOR, COD_SERVICIO_ASIGNADO, COD_ERROR, MENSAJE_TECNICO, MENSAJE_USUARIO, COD_EAP_MENSAJE_DEFINICIONES, COMENTARIO_MENSAJE, USUARIO_REGISTRO, SUCURSAL_REGISTRO, FECHA_REGISTRO, USUARIO_MODIFCACION, SUCURSAL_MODIFICACION, FECHA_MODIFICACION, TZ_LOCK, COD_TIPO_MENSAJE)
	VALUES(codMsjRespServicio, codServicioAsignado, ' ', 'Codigo Exitoso', 'Codigo Exitoso', 14, 'Ninguno', 'TOP1', 701, SYSDATE, NULL, NULL, NULL, 0, 'C');
	

	codServicioAsignado := codServicioAsignado + 1;
	codMsjRespServicio := codMsjRespServicio + 1;
	INSERT INTO GANADERO.SRV_SERVICIOS_ASIGNADOS (IDENTIFICADOR, COD_SERVICIO, COD_SERVICIO_WEB, COD_ESTADO, ALIAS, USUARIO_REGISTRO, SUCURSAL_REGISTRO, FECHA_REGISTRO, USUARIO_MODIFICACION, SUCURSAL_MODIFICACION, FECHA_MODIFICACION, TZ_LOCK, PETICION_FORMATO_ACEPTACION, PETICION_CUERPO, PETICION_SOAP_ACTION, METODO_PETICION, PETICION_TIPO_CONTENIDO, ETIQUETA_RESPUESTA, COD_FORMATO, ETIQUETA_CODIGO_ERROR, ETIQUETA_MSJ_ERROR, SERVICIO_ES_PADRE, COD_PADRE, ORDINAL, COD_TIPO_AUTORIZACION, METODO_DOCUMENTO)
	VALUES(codServicioAsignado, codServicio, 516, 'A', 'deudas', 'WEB', 701, SYSDATE, NULL, NULL, NULL, 0, 'application/json', NULL, NULL, 'POST', NULL, NULL, 1, 'errCode', 'errMsg', 'N', NULL, NULL, 'A', 'N');	
	-- MAPEO DE MSJ AL CLIENTE deudas
	INSERT INTO GANADERO.SRV_MSJ_RESPUESTAS_SERVICIO (IDENTIFICADOR, COD_SERVICIO_ASIGNADO, COD_ERROR, MENSAJE_TECNICO, MENSAJE_USUARIO, COD_EAP_MENSAJE_DEFINICIONES, COMENTARIO_MENSAJE, USUARIO_REGISTRO, SUCURSAL_REGISTRO, FECHA_REGISTRO, USUARIO_MODIFCACION, SUCURSAL_MODIFICACION, FECHA_MODIFICACION, TZ_LOCK, COD_TIPO_MENSAJE)
	VALUES(codMsjRespServicio, codServicioAsignado, ' ', 'Codigo Exitoso', 'Codigo Exitoso', 14, 'Ninguno', 'TOP1', 701, SYSDATE, NULL, NULL, NULL, 0, 'C');
	

	codServicioAsignado := codServicioAsignado + 1;
	codMsjRespServicio := codMsjRespServicio + 1;
	INSERT INTO GANADERO.SRV_SERVICIOS_ASIGNADOS (IDENTIFICADOR, COD_SERVICIO, COD_SERVICIO_WEB, COD_ESTADO, ALIAS, USUARIO_REGISTRO, SUCURSAL_REGISTRO, FECHA_REGISTRO, USUARIO_MODIFICACION, SUCURSAL_MODIFICACION, FECHA_MODIFICACION, TZ_LOCK, PETICION_FORMATO_ACEPTACION, PETICION_CUERPO, PETICION_SOAP_ACTION, METODO_PETICION, PETICION_TIPO_CONTENIDO, ETIQUETA_RESPUESTA, COD_FORMATO, ETIQUETA_CODIGO_ERROR, ETIQUETA_MSJ_ERROR, SERVICIO_ES_PADRE, COD_PADRE, ORDINAL, COD_TIPO_AUTORIZACION, METODO_DOCUMENTO)
	VALUES(codServicioAsignado, codServicio, 132, 'A', 'clientes', 'WEB', 701, SYSDATE, NULL, NULL, NULL, 0, 'application/json', NULL, NULL, 'POST', NULL, NULL, 1, 'errCode', 'errMsg', 'N', NULL, NULL, 'A', 'N');
	-- MAPEO DE MSJ AL CLIENTE clientes
	INSERT INTO GANADERO.SRV_MSJ_RESPUESTAS_SERVICIO (IDENTIFICADOR, COD_SERVICIO_ASIGNADO, COD_ERROR, MENSAJE_TECNICO, MENSAJE_USUARIO, COD_EAP_MENSAJE_DEFINICIONES, COMENTARIO_MENSAJE, USUARIO_REGISTRO, SUCURSAL_REGISTRO, FECHA_REGISTRO, USUARIO_MODIFCACION, SUCURSAL_MODIFICACION, FECHA_MODIFICACION, TZ_LOCK, COD_TIPO_MENSAJE)
	VALUES(codMsjRespServicio, codServicioAsignado, ' ', 'Codigo Exitoso', 'Codigo Exitoso', 14, 'Ninguno', 'TOP1', 701, SYSDATE, NULL, NULL, NULL, 0, 'C');
	
	DBMS_OUTPUT.PUT_LINE('5. Servicio insertado correctamente');
	-- 

	SELECT MAX(IDENTIFICADOR) + 1 INTO codConexionParametro FROM GANADERO.SRV_CONEX_PARAMETROS;
	INSERT INTO GANADERO.SRV_CONEX_PARAMETROS (IDENTIFICADOR, COD_SERVICIO, END_POINT, COD_TIPO_SERVICIOS, COD_TIPO_RESPUESTA, COD_FORMATO_CORREO, USUARIO_INTERNO, CLAVE_INTERNA, USUARIO_EXTERNO, CLAVE_EXTERNA, COD_ESTADO_PARAM_TECNICO, FTP_DIRECTORIO_IMPUT, FTP_DIRECTORIO_OUTPUT, NRO_INTERNO_ASIGNADO, USUARIO_REGISTRO, SUCURSAL_REGISTRO, FECHA_REGISTRO, USUARIO_MODIFICACION, SUCURSAL_MODIFICACION, FECHA_MODIFICACION, TZ_LOCK, COD_FORMATO_RECEPCION_DATOS, COD_ACCION_DE_AFILIACION)
	VALUES(codConexionParametro, codServicio, 'http://172.24.16.60/int/ps/router/', 'R', 'J', 191, NULL, NULL, NULL, NULL, 'H', NULL, NULL, NULL, 'TOP1', 701, SYSDATE, NULL, NULL, NULL, 0, 'A01', 132);
	
	INSERT INTO GANADERO.PARAMETROS_JTS (FUNCIONALIDAD, PARAMETRO, VALOR, TZ_LOCK)
	VALUES('LLAVE_DE_BUSQUEDA_ID_AFILIACION', 'OPCION704', TO_CHAR(codServicio), 0);
	
	COMMIT ;

	-- LAS HABILITACIONES MEDIANTE OPERACIONES TOPAZ. 
	-- 9680 servicios por aplicacion
	-- 6946 servicios por canal
	-- TODO PLAZA COBERTURA  
EXCEPTION
WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE( 'ROLLBACK >');
  DBMS_OUTPUT.PUT_LINE( sqlerrm);
	ROLLBACK;
END;